name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Run tests
        run: uv run pytest -q --maxfail=1 --cov --cov-report=term-missing
